TRAINING_DATA = {
            # Blues
            "water": "blue", "ocean": "blue", "sky": "blue", "sea": "blue",
"lake": "blue", "river": "blue", "rain": "blue", "navy": "blue",
"azure": "blue", "cerulean": "blue", "cobalt": "blue", "sapphire": "blue",
"turquoise": "blue", "cyan": "blue", "teal": "blue", "aqua": "blue",
"periwinkle": "blue", "indigo": "blue", "royal": "blue", "powder": "blue",
"denim": "blue", "jeans": "blue", "blueberry": "blue", "blueprint": "blue",
"bluejay": "blue", "bluebird": "blue", "peacock": "blue", "dolphin": "blue",
"whale": "blue", "shark": "blue", "ice": "blue", "glacier": "blue",
"frost": "blue", "pool": "blue", "lagoon": "blue", "bay": "blue",
"strait": "blue", "channel": "blue", "ford": "blue", "tide": "blue",
"wave": "blue", "surf": "blue", "marine": "blue", "nautical": "blue",
"maritime": "blue", "aquatic": "blue", "hydrangea": "blue", "cornflower": "blue",
"forget-me-not": "blue", "iris": "blue", "delphinium": "blue", "morning-glory": "blue",
"lobelia": "blue", "hyacinth": "blue", "lapis": "blue", "topaz": "blue",
"aquamarine": "blue", "beryl": "blue", "moonstone": "blue", "tanzanite": "blue",
"steel": "blue", "ultramarine": "blue", "prussian": "blue",
"electric": "blue", "neon": "blue", "fluorescent": "blue", "cool": "blue",
"cold": "blue", "arctic": "blue", "polar": "blue", "winter": "blue",
"twilight": "blue", "dusk": "blue", "horizon": "blue", "atmosphere": "blue",
"stratosphere": "blue", "deep": "blue", "depths": "blue", "abyss": "blue",
"pacific": "blue", "atlantic": "blue", "mediterranean": "blue", "caribbean": "blue",
"aegean": "blue", "baltic": "blue", "ink": "blue", "pen": "blue",
"uniform": "blue", "badge": "blue", "flag": "blue", "banner": "blue",
"ribbon": "blue", "medal": "blue", "crystal": "blue", "glass": "blue",
"bottle": "blue", "stained-glass": "blue", "tint": "blue", "shade": "blue",
"hue": "blue", "tone": "blue", "pigment": "blue", "dye": "blue",
"paint": "blue", "watercolor": "blue", "pastel": "blue", "crayon": "blue",
"marker": "blue", "highlighter": "blue", "butterfly": "blue", "dragonfly": "blue",
"kingfisher": "blue", "macaw": "blue", "parrot": "blue", "tang": "blue",
"marlin": "blue", "tuna": "blue", "reef": "blue", 
"submarine": "blue", "yacht": "blue", "sailor": "blue", "captain": "blue",
"anchor": "blue", "harbor": "blue", "port": "blue", "dock": "blue",
"pier": "blue", "lighthouse": "blue", "buoy": "blue", "float": "blue",
"screen": "blue", "monitor": "blue", "light": "blue", "glow": "blue",
"beam": "blue", "ray": "blue", "spectrum": "blue", "wavelength": "blue",
"filter": "blue", "lens": "blue", "prism": "blue", "reflection": "blue",
"shimmer": "blue", "sparkle": "blue", "glitter": "blue", "frost": "blue",
"snowflake": "blue", "icicle": "blue", "bruise": "blue", "vein": "blue",
"blood": "blue", "nobility": "blue", "melancholy": "blue", "sadness": "blue",
"blues": "blue", "monday": "blue", "mood": "blue", "feeling": "blue",
            # Reds
            "fire": "red", "blood": "red", "rose": "red", "cherry": "red",
"strawberry": "red", "tomato": "red", "ruby": "red", "crimson": "red",
"apple": "red", "watermelon": "red", "pomegranate": "red", "raspberry": "red",
"cranberry": "red", "radish": "red", "beet": "red", "bell pepper": "red",
"chili": "red", "paprika": "red", "lobster": "red", "crab": "red",
"cardinal": "red", "ladybug": "red", "poppy": "red", "hibiscus": "red",
"tulip": "red", "geranium": "red", "carnation": "red",
"poinsettia": "red", "amaryllis": "red", "begonia": "red", "camellia": "red",
"mars": "red", "rust": "red", "brick": "red", "clay": "red",
"terracotta": "red", "wine": "red", "ketchup": "red", "salsa": "red",
"sriracha": "red", "tabasco": "red", "lipstick": "red", "nail_polish": "red",
"stop_sign": "red", "traffic_light": "red", "fire_truck": "red", "fire_hydrant": "red",
"mailbox": "red", "red_cross": "red", "valentine": "red", "heart": "red",
"anger": "red", "passion": "red", "love": "red", "danger": "red",
"warning": "red", "alert": "red", "emergency": "red", "exit_sign": "red",
 "garnet": "red", "jasper": "red", "carnelian": "red",
"autumn_leaves": "red", "sunset": "red", "lava": "red", "ember": "red",
"scarlet": "red", "vermillion": "red", "carmine": "red", "burgundy": "red",
"maroon": "red", "rouge": "red", "claret": "red", "cerise": "red",
"magenta": "red", "fuchsia": "red", "red_velvet": "red", "red_bean": "red",
"goji_berry": "red", "red_currant": "red", "blood_orange": "red", "grape": "red",
"red_onion": "red", "red_cabbage": "red", "rhubarb": "red", "red_lentil": "red",
"saffron_thread": "red", "red_snapper": "red", "red_meat": "red", "steak": "red",
"prosciutto": "red", "salami": "red", "chorizo": "red", "red_flag": "red",
"red_carpet": "red", "red_ribbon": "red", "red_thread": "red",
"red_crayon": "red", "red_marker": "red", "red_paint": "red",
"robin breast": "red", "rooster comb": "red", "fox": "red", "red_panda": "red",
"flamingo": "red", "red_ant": "red", "red_spider": "red", "red_squirrel": "red",
            # Greens
            "grass": "green", "leaf": "green", "tree": "green", "forest": "green",
"plant": "green", "moss": "green", "emerald": "green", "lime": "green",
"fern": "green", "ivy": "green", "clover": "green", "bamboo": "green",
"cactus": "green", "succulent": "green", "algae": "green", "seaweed": "green",
"jade": "green", "malachite": "green", "peridot": "green", "aventurine": "green",
"avocado": "green", "cucumber": "green", "lettuce": "green", "spinach": "green",
"broccoli": "green", "kale": "green", "peas": "green", "celery": "green",
"basil": "green", "mint": "green", "parsley": "green", "cilantro": "green",
"sage": "green", "thyme": "green", "oregano": "green", "rosemary": "green",
"olive": "green", "pickle": "green", "zucchini": "green", "kiwi": "green", "honeydew": "green",
"frog": "green", "lizard": "green", "snake": "green", "chameleon": "green",
"grasshopper": "green", "mantis": "green", "caterpillar": "green", "turtle": "green",
"parrot": "green", "peacock": "green", "hummingbird": "green", "iguana": "green",
"dollar": "green", "money": "green", "cash": "green", "currency": "green",
"traffic_light": "green", "go_signal": "green", "exit_sign": "green", "recycling": "green",
"army": "green", "military": "green", "camouflage": "green", "uniform": "green",
"spring": "green", "nature": "green", "ecology": "green", "environment": "green",
"pistachio": "green", "matcha": "green", "wasabi": "green", "pesto": "green",
"shamrock": "green", "four_leaf_clover": "green", "ireland": "green", "st_patricks": "green",
"field": "green", "meadow": "green", "lawn": "green", "golf_course": "green",
"jungle": "green", "rainforest": "green", "canopy": "green", "undergrowth": "green",
"kelp": "green", "pond_scum": "green", "lily_pad": "green", "duckweed": "green",
"green_tea": "green", "mountain_dew": "green", "sprite": "green", "absinthe": "green",
"teal": "green", "seafoam": "green", "aquamarine": "green", "turquoise": "green",
"chartreuse": "green", "viridian": "green", "verdigris": "green", "celadon": "green",
"hunter": "green", "forest": "green", "pine": "green", "evergreen": "green",
"neon": "green", "electric": "green", "fluorescent": "green", "glow": "green",
"zombie": "green", "alien": "green", "hulk": "green", "shrek": "green",
"tennis_ball": "green", "pool_table": "green", "chalkboard": "green",
            # Yellows
            "sun": "yellow", "banana": "yellow", "lemon": "yellow", "gold": "yellow",
"corn": "yellow", "butter": "yellow", "honey": "yellow", "blonde": "yellow",
"sunflower": "yellow", "daffodil": "yellow", "canary": "yellow", "mustard": "yellow",
"cheese": "yellow", "egg yolk": "yellow", "pineapple": "yellow", "squash": "yellow",
"marigold": "yellow", "buttercup": "yellow", "dandelion": "yellow",
"taxi": "yellow", "school bus": "yellow", "rubber duck": "yellow", "highlighter": "yellow",
 "topaz": "yellow", "citrine": "yellow", "sulfur": "yellow",
"brass": "yellow", "bronze": "yellow", "saffron": "yellow", "turmeric": "yellow",
"bee": "yellow", "wasp": "yellow", "chick": "yellow",
"duckling": "yellow", "butterfly": "yellow", "yellowfin tuna": "yellow", "python": "yellow",
"mango": "yellow", "papaya": "yellow", "peach": "yellow", "apricot": "yellow",
"grapefruit": "yellow", "starfruit": "yellow", "passion fruit": "yellow", "durian": "yellow",
"macaroni": "yellow", "custard": "yellow", "margarine": "yellow", "cheddar": "yellow",
"popcorn": "yellow", "chips": "yellow", "fries": "yellow", "cornbread": "yellow",
"pencil": "yellow", "sticky note": "yellow", "caution tape": "yellow", "yield sign": "yellow",
"hard hat": "yellow", "raincoat": "yellow", "life jacket": "yellow", "tennis ball": "yellow",
"emoji": "yellow", "smiley face": "yellow", "pac-man": "yellow", "pikachu": "yellow",
"lightning": "yellow", "sand": "yellow", "wheat": "yellow", "straw": "yellow",
"champagne": "yellow", "beer": "yellow", "lemonade": "yellow", "yellow pepper": "yellow",
"banana pepper": "yellow", "yellow onion": "yellow", "yellow beans": "yellow", "chickpeas": "yellow",
"yellow lentils": "yellow", "cornmeal": "yellow", "polenta": "yellow", "couscous": "yellow",
"yellow cake": "yellow", "lemon curd": "yellow", "butterscotch": "yellow", "caramel": "yellow",
"yellow rose": "yellow", "forsythia": "yellow", "primrose": "yellow", "yarrow": "yellow",
"goldenrod": "yellow", "sunburst": "yellow", "yellow flag": "yellow", "yellow card": "yellow",
"yellow pages": "yellow", "yellow jacket": "yellow", "yellow fever": "yellow", "jaundice": "yellow",
            # Whites
            "snow": "white", "chalk": "white", "marble": "white", "porcelain": "white", "foam": "white",
"frost": "white", "ice": "white", "cotton": "white", "linen": "white",
"teeth": "white", "bones": "white", "egg_white": "white", "flour": "white",
"rice": "white", "coconut": "white", "vanilla_ice_cream": "white", "whipped_cream": "white",
"mayonnaise": "white", "yogurt": "white", "mozzarella": "white", "feta_cheese": "white",
"cauliflower": "white", "garlic": "white", "onion": "white", "mushroom": "white",
"daisy": "white", "lily": "white", "jasmine": "white", "gardenia": "white",
"swan": "white", "dove": "white", "polar_bear": "white", "arctic_fox": "white",
"beluga_whale": "white", "seagull": "white", "cockatoo": "white", "albino_animals": "white",
"limestone": "white", "quartz": "white", "alabaster": "white", "gypsum": "white",
"wedding_dress": "white", "lab_coat": "white", "chef_hat": "white", "sailor_uniform": "white",
"bandage": "white", "plaster": "white", "aspirin": "white", "pills": "white",
"lighthouse": "white", "picket_fence": "white", "whiteboard": "white", "projector_screen": "white",
"moonlight": "white", "stars": "white", "lightning": "white", "foam_rubber": "white",
"styrofoam": "white", "tissue_paper": "white", "toilet_paper": "white", "napkins": "white",
"bedsheets": "white", "pillowcase": "white", "towels": "white", "bathrobe": "white",
"ping_pong_ball": "white", "golf_ball": "white", "baseball": "white", "volleyball": "white",
"white_chocolate": "white", "meringue": "white", "marshmallow": "white", "popcorn": "white",
"birch_bark": "white", "white_sand": "white", "sea_foam": "white", "dandelion_seeds": "white",
"cumulus_clouds": "white", "fog": "white", "mist": "white", "steam": "white",
"white_wine": "white", "champagne_foam": "white", "milk_foam": "white", "soap_suds": "white",
"white_flag": "white", "surrender_flag": "white", "peace_dove": "white", "blank_canvas": "white",
"parchment": "white", "vellum": "white", "white_crayon": "white", "correction_fluid": "white",
"white_paint": "white", "primer": "white", "gesso": "white", "titanium_white": "white",
            # Blacks
          "midnight": "black", "obsidian": "black", "charcoal": "black", "soot": "black", "tar": "black",
"pitch": "black", "graphite": "black", "carbon": "black", "oil": "black",
"panther": "black", "crow": "black", "blackbird": "black", "bat": "black",
"beetle": "black", "widow": "black", "mamba": "black", "bear": "black",
"licorice": "black", "coffee": "black", "molasses": "black", "blackberry": "black",
"olive": "black", "sesame": "black", "caviar": "black", "truffle": "black",
"velvet": "black", "silk": "black", "leather": "black", "suede": "black",
"patent": "black", "latex": "black", "rubber": "black", "vinyl": "black",
"asphalt": "black", "bitumen": "black", "basalt": "black", "shale": "black",
"slate": "black", "granite": "black", "jet": "black",
"space": "black", "void": "black", "abyss": "black", "darkness": "black",
"eclipse": "black", "pupil": "black", "hole": "black", "vacuum": "black",
"tuxedo": "black", "suit": "black", "tie": "black", "dress": "black",
"mascara": "black", "eyeliner": "black", "kohl": "black", "henna": "black",
"piano": "black", "keys": "black", "vinyl": "black", "record": "black",
"tire": "black", "wheel": "black", "rim": "black", "chrome": "black",
"screen": "black", "monitor": "black", "television": "black", "phone": "black",
"pepper": "black", "peppercorn": "black", "bean": "black", "rice": "black",
"quinoa": "black", "lentil": "black", "pudding": "black",
"squid": "black", "cuttlefish": "black", "octopus": "black", "mussel": "black",
"pearl": "black", "opal": "black", "tourmaline": "black", "spinel": "black",
"cat": "black", "dog": "black", "horse": "black", "stallion": "black",
"sheep": "black", "goat": "black", "bull": "black", "rooster": "black",
"smoke": "black", "smog": "black", "exhaust": "black", "fume": "black",
"storm": "black", "thunder": "black", "cloud": "black", "tempest": "black",
"mourning": "black", "funeral": "black", "grief": "black", "sorrow": "black",
"formal": "black", "elegant": "black", "sophisticated": "black", "sleek": "black",
"matte": "black", "glossy": "black", "shiny": "black", "polished": "black",
"metallic": "black", "iridescent": "black", "lustrous": "black", "shimmer": "black",
            # Oranges
            "orange": "orange", "pumpkin": "orange", "carrot": "orange", "sunset": "orange",
"tangerine": "orange", "apricot": "orange", "amber": "orange", "rust": "orange",
"persimmon": "orange", "cantaloupe": "orange", "papaya": "orange", "peach": "orange",
"nectarine": "orange", "clementine": "orange", "mandarin": "orange", "kumquat": "orange",
"goldfish": "orange", "monarch": "orange", "tiger": "orange", "fox": "orange",
"orangutan": "orange", "clownfish": "orange", "koi": "orange", "salamander": "orange",
"marigold": "orange", "poppy": "orange", "nasturtium": "orange", "zinnia": "orange",
"dahlia": "orange", "calendula": "orange", "cosmos": "orange",
"basketball": "orange", "cone": "orange", "lifejacket": "orange", "safety vest": "orange",
"traffic light": "orange", "construction sign": "orange", "buoy": "orange", "flare": "orange",
"cheddar": "orange", "marmalade": "orange", "turmeric": "orange", "paprika": "orange",
"saffron": "orange", "curry": "orange", "sweet potato": "orange", "butternut": "orange",
"fire": "orange", "flame": "orange", "lava": "orange", "ember": "orange",
"autumn": "orange", "fall leaves": "orange", "harvest": "orange", "maple leaf": "orange",
"coral": "orange", "starfish": "orange", "sea sponge": "orange", "anemone": "orange",
"terracotta": "orange", "clay": "orange", "brick": "orange", "pottery": "orange",
"ginger": "orange", "yam": "orange", "squash": "orange",
"habanero": "orange", "scotch bonnet": "orange", "bird of paradise": "orange", "lily": "orange",
"sand": "orange", "desert": "orange", "canyon": "orange", "sandstone": "orange",
"copper": "orange", "bronze": "orange", "brass": "orange", "ochre": "orange",
            # Purples
            "wisteria": "purple", "periwinkle": "purple", "heather": "purple",
"verbena": "purple", "clematis": "purple", "petunia": "purple", "pansy": "purple",
"aster": "purple", "foxglove": "purple", "morning glory": "purple", "sweet pea": "purple",
"crocus": "purple", "hyacinth": "purple", "delphinium": "purple", "bellflower": "purple",
"blackberry": "purple", "elderberry": "purple", "acai": "purple", "passion fruit": "purple",
"fig": "purple", "purple cabbage": "purple", "purple potato": "purple", "purple carrot": "purple",
"purple cauliflower": "purple", "purple asparagus": "purple", "purple onion": "purple", "taro": "purple",
"fluorite": "purple", "charoite": "purple", "sugilite": "purple", "lepidolite": "purple",
"purple sapphire": "purple", "iolite": "purple", "tanzanite": "purple", "purple tourmaline": "purple",
"mauve": "purple", "magenta": "purple", "indigo": "purple", "royal purple": "purple",
"byzantium": "purple", "tyrian purple": "purple", "electric purple": "purple", "deep purple": "purple",
"purple finch": "purple", "purple martin": "purple", "purple emperor butterfly": "purple", "purple sea urchin": "purple",
"purple starfish": "purple", "purple tang fish": "purple", "purple frog": "purple", "violet-backed starling": "purple",
"mulberry": "purple", "boysenberry": "purple", "purple corn": "purple", "purple sweet potato": "purple",
"purple basil": "purple", "purple kale": "purple", "purple brussels sprouts": "purple", "radicchio": "purple",
"purple jade": "purple", "purple agate": "purple", "purple calcite": "purple", "purple quartz": "purple",
"purple garnet": "purple", "purple spinel": "purple", "kunzite": "purple", "purple beryl": "purple",
"heliotrope": "purple", "fuchsia": "purple", "phlox": "purple", "purple sage": "purple",
"jacaranda": "purple", "purple heart wood": "purple", "purple shamrock": "purple", "purple passion plant": "purple"
        }